//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 11:28:55 AM BRST 
//


package br.com.getnet.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ASCGDOCComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ASCGDOCComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BCARQ" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}BCARQComplexType"/>
 *         &lt;element name="SISARQ" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}SISARQComplexType"/>
 *         &lt;element name="ESTARQ" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}ESTARQSimpleType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ASCGDOCComplexType", propOrder = {
    "bcarq",
    "sisarq",
    "estarq"
})
public class ASCGDOCComplexType {

    @XmlElement(name = "BCARQ", required = true)
    protected BCARQComplexType bcarq;
    @XmlElement(name = "SISARQ", required = true)
    protected SISARQComplexType sisarq;
    @XmlElement(name = "ESTARQ")
    protected String estarq;

    /**
     * Gets the value of the bcarq property.
     * 
     * @return
     *     possible object is
     *     {@link BCARQComplexType }
     *     
     */
    public BCARQComplexType getBCARQ() {
        return bcarq;
    }

    /**
     * Sets the value of the bcarq property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCARQComplexType }
     *     
     */
    public void setBCARQ(BCARQComplexType value) {
        this.bcarq = value;
    }

    /**
     * Gets the value of the sisarq property.
     * 
     * @return
     *     possible object is
     *     {@link SISARQComplexType }
     *     
     */
    public SISARQComplexType getSISARQ() {
        return sisarq;
    }

    /**
     * Sets the value of the sisarq property.
     * 
     * @param value
     *     allowed object is
     *     {@link SISARQComplexType }
     *     
     */
    public void setSISARQ(SISARQComplexType value) {
        this.sisarq = value;
    }

    /**
     * Gets the value of the estarq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getESTARQ() {
        return estarq;
    }

    /**
     * Sets the value of the estarq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setESTARQ(String value) {
        this.estarq = value;
    }

}
