//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 11:28:55 AM BRST 
//


package br.com.getnet.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ASCG026ComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ASCG026ComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Grupo_ASCG026_Agend" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}Grupo_ASCG026_AgendComplexType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ASCG026ComplexType", propOrder = {
    "grupoASCG026Agend"
})
public class ASCG026ComplexType {

    @XmlElement(name = "Grupo_ASCG026_Agend", required = true)
    protected GrupoASCG026AgendComplexType grupoASCG026Agend;

    /**
     * Gets the value of the grupoASCG026Agend property.
     * 
     * @return
     *     possible object is
     *     {@link GrupoASCG026AgendComplexType }
     *     
     */
    public GrupoASCG026AgendComplexType getGrupoASCG026Agend() {
        return grupoASCG026Agend;
    }

    /**
     * Sets the value of the grupoASCG026Agend property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrupoASCG026AgendComplexType }
     *     
     */
    public void setGrupoASCG026Agend(GrupoASCG026AgendComplexType value) {
        this.grupoASCG026Agend = value;
    }

}
