//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 11:28:55 AM BRST 
//


package br.com.getnet.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ASCG026RETComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ASCG026RETComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Grupo_ASCG026RET_AgendActo" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}Grupo_ASCG026RET_AgendActoComplexType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Grupo_ASCG026RET_AgendRecsdo" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}Grupo_ASCG026RET_AgendRecsdoComplexType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ASCG026RETComplexType", propOrder = {
    "grupoASCG026RETAgendActo",
    "grupoASCG026RETAgendRecsdo"
})
public class ASCG026RETComplexType {

    @XmlElement(name = "Grupo_ASCG026RET_AgendActo")
    protected List<GrupoASCG026RETAgendActoComplexType> grupoASCG026RETAgendActo;
    @XmlElement(name = "Grupo_ASCG026RET_AgendRecsdo")
    protected List<GrupoASCG026RETAgendRecsdoComplexType> grupoASCG026RETAgendRecsdo;

    /**
     * Gets the value of the grupoASCG026RETAgendActo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the grupoASCG026RETAgendActo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGrupoASCG026RETAgendActo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GrupoASCG026RETAgendActoComplexType }
     * 
     * 
     */
    public List<GrupoASCG026RETAgendActoComplexType> getGrupoASCG026RETAgendActo() {
        if (grupoASCG026RETAgendActo == null) {
            grupoASCG026RETAgendActo = new ArrayList<GrupoASCG026RETAgendActoComplexType>();
        }
        return this.grupoASCG026RETAgendActo;
    }

    /**
     * Gets the value of the grupoASCG026RETAgendRecsdo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the grupoASCG026RETAgendRecsdo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGrupoASCG026RETAgendRecsdo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GrupoASCG026RETAgendRecsdoComplexType }
     * 
     * 
     */
    public List<GrupoASCG026RETAgendRecsdoComplexType> getGrupoASCG026RETAgendRecsdo() {
        if (grupoASCG026RETAgendRecsdo == null) {
            grupoASCG026RETAgendRecsdo = new ArrayList<GrupoASCG026RETAgendRecsdoComplexType>();
        }
        return this.grupoASCG026RETAgendRecsdo;
    }

}
