//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 11:28:55 AM BRST 
//


package br.com.getnet.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for BCARQComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BCARQComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NomArq" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}Nome"/>
 *         &lt;element name="NumCtrlEmis" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}ControleIF"/>
 *         &lt;element name="NumCtrlDestOr" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}ControleIF" minOccurs="0"/>
 *         &lt;element name="ISPBEmissor" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}CNPJBase"/>
 *         &lt;element name="ISPBDestinatario" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}CNPJBase"/>
 *         &lt;element name="DtHrArq" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}DataHora"/>
 *         &lt;element name="SitCons" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}SitCons" minOccurs="0"/>
 *         &lt;element name="Grupo_Seq" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}Grupo_SeqComplexType" minOccurs="0"/>
 *         &lt;element name="DtRef" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}Data"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BCARQComplexType", propOrder = {
    "nomArq",
    "numCtrlEmis",
    "numCtrlDestOr",
    "ispbEmissor",
    "ispbDestinatario",
    "dtHrArq",
    "sitCons",
    "grupoSeq",
    "dtRef"
})
public class BCARQComplexType {

    @XmlElement(name = "NomArq", required = true)
    protected String nomArq;
    @XmlElement(name = "NumCtrlEmis", required = true)
    protected String numCtrlEmis;
    @XmlElement(name = "NumCtrlDestOr")
    protected String numCtrlDestOr;
    @XmlElement(name = "ISPBEmissor", required = true)
    protected String ispbEmissor;
    @XmlElement(name = "ISPBDestinatario", required = true)
    protected String ispbDestinatario;
    @XmlElement(name = "DtHrArq", required = true)
    protected XMLGregorianCalendar dtHrArq;
    @XmlElement(name = "SitCons")
    protected BigInteger sitCons;
    @XmlElement(name = "Grupo_Seq")
    protected GrupoSeqComplexType grupoSeq;
    @XmlElement(name = "DtRef", required = true)
    protected XMLGregorianCalendar dtRef;

    /**
     * Gets the value of the nomArq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomArq() {
        return nomArq;
    }

    /**
     * Sets the value of the nomArq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomArq(String value) {
        this.nomArq = value;
    }

    /**
     * Gets the value of the numCtrlEmis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumCtrlEmis() {
        return numCtrlEmis;
    }

    /**
     * Sets the value of the numCtrlEmis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumCtrlEmis(String value) {
        this.numCtrlEmis = value;
    }

    /**
     * Gets the value of the numCtrlDestOr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumCtrlDestOr() {
        return numCtrlDestOr;
    }

    /**
     * Sets the value of the numCtrlDestOr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumCtrlDestOr(String value) {
        this.numCtrlDestOr = value;
    }

    /**
     * Gets the value of the ispbEmissor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISPBEmissor() {
        return ispbEmissor;
    }

    /**
     * Sets the value of the ispbEmissor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISPBEmissor(String value) {
        this.ispbEmissor = value;
    }

    /**
     * Gets the value of the ispbDestinatario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISPBDestinatario() {
        return ispbDestinatario;
    }

    /**
     * Sets the value of the ispbDestinatario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISPBDestinatario(String value) {
        this.ispbDestinatario = value;
    }

    /**
     * Gets the value of the dtHrArq property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtHrArq() {
        return dtHrArq;
    }

    /**
     * Sets the value of the dtHrArq property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtHrArq(XMLGregorianCalendar value) {
        this.dtHrArq = value;
    }

    /**
     * Gets the value of the sitCons property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSitCons() {
        return sitCons;
    }

    /**
     * Sets the value of the sitCons property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSitCons(BigInteger value) {
        this.sitCons = value;
    }

    /**
     * Gets the value of the grupoSeq property.
     * 
     * @return
     *     possible object is
     *     {@link GrupoSeqComplexType }
     *     
     */
    public GrupoSeqComplexType getGrupoSeq() {
        return grupoSeq;
    }

    /**
     * Sets the value of the grupoSeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrupoSeqComplexType }
     *     
     */
    public void setGrupoSeq(GrupoSeqComplexType value) {
        this.grupoSeq = value;
    }

    /**
     * Gets the value of the dtRef property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtRef() {
        return dtRef;
    }

    /**
     * Sets the value of the dtRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtRef(XMLGregorianCalendar value) {
        this.dtRef = value;
    }

}
