//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 11:28:55 AM BRST 
//


package br.com.getnet.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BCARQERRComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BCARQERRComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NomArq" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}NomArqCodErr_ComplexType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BCARQERRComplexType", propOrder = {
    "nomArq"
})
public class BCARQERRComplexType {

    @XmlElement(name = "NomArq", required = true)
    protected NomArqCodErrComplexType nomArq;

    /**
     * Gets the value of the nomArq property.
     * 
     * @return
     *     possible object is
     *     {@link NomArqCodErrComplexType }
     *     
     */
    public NomArqCodErrComplexType getNomArq() {
        return nomArq;
    }

    /**
     * Sets the value of the nomArq property.
     * 
     * @param value
     *     allowed object is
     *     {@link NomArqCodErrComplexType }
     *     
     */
    public void setNomArq(NomArqCodErrComplexType value) {
        this.nomArq = value;
    }

}
