//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 11:28:55 AM BRST 
//


package br.com.getnet.xml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Grupo_ASCG026_AgendComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Grupo_ASCG026_AgendComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CNPJBaseCreddr" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}CNPJBase"/>
 *         &lt;element name="CNPJCreddr" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}CNPJ"/>
 *         &lt;element name="ISPBIFCredr" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}CNPJBase"/>
 *         &lt;element name="AgCreddr" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}Agencia"/>
 *         &lt;element name="CtCreddr" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}CtBancaria"/>
 *         &lt;element name="NomCreddr" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}Nome"/>
 *         &lt;element name="Grupo_ASCG026_Centrlz" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}Grupo_ASCG026_CentrlzComplexType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Grupo_ASCG026_AgendComplexType", propOrder = {
    "cnpjBaseCreddr",
    "cnpjCreddr",
    "ispbifCredr",
    "agCreddr",
    "ctCreddr",
    "nomCreddr",
    "grupoASCG026Centrlz"
})
public class GrupoASCG026AgendComplexType {

    @XmlElement(name = "CNPJBaseCreddr", required = true)
    protected String cnpjBaseCreddr;
    @XmlElement(name = "CNPJCreddr", required = true)
    protected String cnpjCreddr;
    @XmlElement(name = "ISPBIFCredr", required = true)
    protected String ispbifCredr;
    @XmlElement(name = "AgCreddr", required = true)
    protected BigInteger agCreddr;
    @XmlElement(name = "CtCreddr", required = true)
    protected BigInteger ctCreddr;
    @XmlElement(name = "NomCreddr", required = true)
    protected String nomCreddr;
    @XmlElement(name = "Grupo_ASCG026_Centrlz", required = true)
    protected List<GrupoASCG026CentrlzComplexType> grupoASCG026Centrlz;

    /**
     * Gets the value of the cnpjBaseCreddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCNPJBaseCreddr() {
        return cnpjBaseCreddr;
    }

    /**
     * Sets the value of the cnpjBaseCreddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCNPJBaseCreddr(String value) {
        this.cnpjBaseCreddr = value;
    }

    /**
     * Gets the value of the cnpjCreddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCNPJCreddr() {
        return cnpjCreddr;
    }

    /**
     * Sets the value of the cnpjCreddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCNPJCreddr(String value) {
        this.cnpjCreddr = value;
    }

    /**
     * Gets the value of the ispbifCredr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISPBIFCredr() {
        return ispbifCredr;
    }

    /**
     * Sets the value of the ispbifCredr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISPBIFCredr(String value) {
        this.ispbifCredr = value;
    }

    /**
     * Gets the value of the agCreddr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAgCreddr() {
        return agCreddr;
    }

    /**
     * Sets the value of the agCreddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAgCreddr(BigInteger value) {
        this.agCreddr = value;
    }

    /**
     * Gets the value of the ctCreddr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCtCreddr() {
        return ctCreddr;
    }

    /**
     * Sets the value of the ctCreddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCtCreddr(BigInteger value) {
        this.ctCreddr = value;
    }

    /**
     * Gets the value of the nomCreddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomCreddr() {
        return nomCreddr;
    }

    /**
     * Sets the value of the nomCreddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomCreddr(String value) {
        this.nomCreddr = value;
    }

    /**
     * Gets the value of the grupoASCG026Centrlz property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the grupoASCG026Centrlz property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGrupoASCG026Centrlz().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GrupoASCG026CentrlzComplexType }
     * 
     * 
     */
    public List<GrupoASCG026CentrlzComplexType> getGrupoASCG026Centrlz() {
        if (grupoASCG026Centrlz == null) {
            grupoASCG026Centrlz = new ArrayList<GrupoASCG026CentrlzComplexType>();
        }
        return this.grupoASCG026Centrlz;
    }

}
