//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 11:28:55 AM BRST 
//


package br.com.getnet.xml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Grupo_ASCG026_CentrlzComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Grupo_ASCG026_CentrlzComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NumCtrlCreddrCentrlz" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}ControleIF"/>
 *         &lt;element name="TpPessoaCentrlz" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}TpPessoa"/>
 *         &lt;element name="CNPJ_CPFCentrlz" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}CNPJ_CPF"/>
 *         &lt;element name="CodCentrlz" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}CodCentrlz"/>
 *         &lt;element name="AgCentrlz" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}Agencia"/>
 *         &lt;element name="CtCentrlz" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}CtBancaria"/>
 *         &lt;element name="Grupo_ASCG026_PontoVenda" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}Grupo_ASCG026_PontoVendaComplexType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Grupo_ASCG026_CentrlzComplexType", propOrder = {
    "numCtrlCreddrCentrlz",
    "tpPessoaCentrlz",
    "cnpjcpfCentrlz",
    "codCentrlz",
    "agCentrlz",
    "ctCentrlz",
    "grupoASCG026PontoVenda"
})
public class GrupoASCG026CentrlzComplexType {

    @XmlElement(name = "NumCtrlCreddrCentrlz", required = true)
    protected String numCtrlCreddrCentrlz;
    @XmlElement(name = "TpPessoaCentrlz", required = true)
    protected String tpPessoaCentrlz;
    @XmlElement(name = "CNPJ_CPFCentrlz", required = true)
    protected String cnpjcpfCentrlz;
    @XmlElement(name = "CodCentrlz", required = true)
    protected String codCentrlz;
    @XmlElement(name = "AgCentrlz", required = true)
    protected BigInteger agCentrlz;
    @XmlElement(name = "CtCentrlz", required = true)
    protected BigInteger ctCentrlz;
    @XmlElement(name = "Grupo_ASCG026_PontoVenda", required = true)
    protected List<GrupoASCG026PontoVendaComplexType> grupoASCG026PontoVenda;

    /**
     * Gets the value of the numCtrlCreddrCentrlz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumCtrlCreddrCentrlz() {
        return numCtrlCreddrCentrlz;
    }

    /**
     * Sets the value of the numCtrlCreddrCentrlz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumCtrlCreddrCentrlz(String value) {
        this.numCtrlCreddrCentrlz = value;
    }

    /**
     * Gets the value of the tpPessoaCentrlz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTpPessoaCentrlz() {
        return tpPessoaCentrlz;
    }

    /**
     * Sets the value of the tpPessoaCentrlz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTpPessoaCentrlz(String value) {
        this.tpPessoaCentrlz = value;
    }

    /**
     * Gets the value of the cnpjcpfCentrlz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCNPJCPFCentrlz() {
        return cnpjcpfCentrlz;
    }

    /**
     * Sets the value of the cnpjcpfCentrlz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCNPJCPFCentrlz(String value) {
        this.cnpjcpfCentrlz = value;
    }

    /**
     * Gets the value of the codCentrlz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodCentrlz() {
        return codCentrlz;
    }

    /**
     * Sets the value of the codCentrlz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodCentrlz(String value) {
        this.codCentrlz = value;
    }

    /**
     * Gets the value of the agCentrlz property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAgCentrlz() {
        return agCentrlz;
    }

    /**
     * Sets the value of the agCentrlz property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAgCentrlz(BigInteger value) {
        this.agCentrlz = value;
    }

    /**
     * Gets the value of the ctCentrlz property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCtCentrlz() {
        return ctCentrlz;
    }

    /**
     * Sets the value of the ctCentrlz property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCtCentrlz(BigInteger value) {
        this.ctCentrlz = value;
    }

    /**
     * Gets the value of the grupoASCG026PontoVenda property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the grupoASCG026PontoVenda property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGrupoASCG026PontoVenda().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GrupoASCG026PontoVendaComplexType }
     * 
     * 
     */
    public List<GrupoASCG026PontoVendaComplexType> getGrupoASCG026PontoVenda() {
        if (grupoASCG026PontoVenda == null) {
            grupoASCG026PontoVenda = new ArrayList<GrupoASCG026PontoVendaComplexType>();
        }
        return this.grupoASCG026PontoVenda;
    }

}
