//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 11:28:55 AM BRST 
//


package br.com.getnet.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Grupo_ASCG026_CentrlzRecsdoComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Grupo_ASCG026_CentrlzRecsdoComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NumCtrlCreddrCentrlz" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}ControleIFCodErr"/>
 *         &lt;element name="TpPessoaCentrlz" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}TpPessoaCodErr"/>
 *         &lt;element name="CNPJ_CPFCentrlz" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}CNPJ_CPFCodErr"/>
 *         &lt;element name="CodCentrlz" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}CodCentrlzCodErr"/>
 *         &lt;element name="AgCentrlz" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}AgenciaCodErr"/>
 *         &lt;element name="CtCentrlz" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}CtBancariaCodErr"/>
 *         &lt;element name="Grupo_ASCG026_PontoVendaRecsdo" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}Grupo_ASCG026_PontoVendaComplexType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CodErro" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}CodErro" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Grupo_ASCG026_CentrlzRecsdoComplexType", propOrder = {
    "numCtrlCreddrCentrlz",
    "tpPessoaCentrlz",
    "cnpjcpfCentrlz",
    "codCentrlz",
    "agCentrlz",
    "ctCentrlz",
    "grupoASCG026PontoVendaRecsdo"
})
public class GrupoASCG026CentrlzRecsdoComplexType {

    @XmlElement(name = "NumCtrlCreddrCentrlz", required = true)
    protected ControleIFCodErr numCtrlCreddrCentrlz;
    @XmlElement(name = "TpPessoaCentrlz", required = true)
    protected TpPessoaCodErr tpPessoaCentrlz;
    @XmlElement(name = "CNPJ_CPFCentrlz", required = true)
    protected CNPJCPFCodErr cnpjcpfCentrlz;
    @XmlElement(name = "CodCentrlz", required = true)
    protected CodCentrlzCodErr codCentrlz;
    @XmlElement(name = "AgCentrlz", required = true)
    protected AgenciaCodErr agCentrlz;
    @XmlElement(name = "CtCentrlz", required = true)
    protected CtBancariaCodErr ctCentrlz;
    @XmlElement(name = "Grupo_ASCG026_PontoVendaRecsdo", required = true)
    protected List<GrupoASCG026PontoVendaComplexType> grupoASCG026PontoVendaRecsdo;
    @XmlAttribute(name = "CodErro")
    protected String codErro;

    /**
     * Gets the value of the numCtrlCreddrCentrlz property.
     * 
     * @return
     *     possible object is
     *     {@link ControleIFCodErr }
     *     
     */
    public ControleIFCodErr getNumCtrlCreddrCentrlz() {
        return numCtrlCreddrCentrlz;
    }

    /**
     * Sets the value of the numCtrlCreddrCentrlz property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControleIFCodErr }
     *     
     */
    public void setNumCtrlCreddrCentrlz(ControleIFCodErr value) {
        this.numCtrlCreddrCentrlz = value;
    }

    /**
     * Gets the value of the tpPessoaCentrlz property.
     * 
     * @return
     *     possible object is
     *     {@link TpPessoaCodErr }
     *     
     */
    public TpPessoaCodErr getTpPessoaCentrlz() {
        return tpPessoaCentrlz;
    }

    /**
     * Sets the value of the tpPessoaCentrlz property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpPessoaCodErr }
     *     
     */
    public void setTpPessoaCentrlz(TpPessoaCodErr value) {
        this.tpPessoaCentrlz = value;
    }

    /**
     * Gets the value of the cnpjcpfCentrlz property.
     * 
     * @return
     *     possible object is
     *     {@link CNPJCPFCodErr }
     *     
     */
    public CNPJCPFCodErr getCNPJCPFCentrlz() {
        return cnpjcpfCentrlz;
    }

    /**
     * Sets the value of the cnpjcpfCentrlz property.
     * 
     * @param value
     *     allowed object is
     *     {@link CNPJCPFCodErr }
     *     
     */
    public void setCNPJCPFCentrlz(CNPJCPFCodErr value) {
        this.cnpjcpfCentrlz = value;
    }

    /**
     * Gets the value of the codCentrlz property.
     * 
     * @return
     *     possible object is
     *     {@link CodCentrlzCodErr }
     *     
     */
    public CodCentrlzCodErr getCodCentrlz() {
        return codCentrlz;
    }

    /**
     * Sets the value of the codCentrlz property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodCentrlzCodErr }
     *     
     */
    public void setCodCentrlz(CodCentrlzCodErr value) {
        this.codCentrlz = value;
    }

    /**
     * Gets the value of the agCentrlz property.
     * 
     * @return
     *     possible object is
     *     {@link AgenciaCodErr }
     *     
     */
    public AgenciaCodErr getAgCentrlz() {
        return agCentrlz;
    }

    /**
     * Sets the value of the agCentrlz property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgenciaCodErr }
     *     
     */
    public void setAgCentrlz(AgenciaCodErr value) {
        this.agCentrlz = value;
    }

    /**
     * Gets the value of the ctCentrlz property.
     * 
     * @return
     *     possible object is
     *     {@link CtBancariaCodErr }
     *     
     */
    public CtBancariaCodErr getCtCentrlz() {
        return ctCentrlz;
    }

    /**
     * Sets the value of the ctCentrlz property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtBancariaCodErr }
     *     
     */
    public void setCtCentrlz(CtBancariaCodErr value) {
        this.ctCentrlz = value;
    }

    /**
     * Gets the value of the grupoASCG026PontoVendaRecsdo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the grupoASCG026PontoVendaRecsdo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGrupoASCG026PontoVendaRecsdo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GrupoASCG026PontoVendaComplexType }
     * 
     * 
     */
    public List<GrupoASCG026PontoVendaComplexType> getGrupoASCG026PontoVendaRecsdo() {
        if (grupoASCG026PontoVendaRecsdo == null) {
            grupoASCG026PontoVendaRecsdo = new ArrayList<GrupoASCG026PontoVendaComplexType>();
        }
        return this.grupoASCG026PontoVendaRecsdo;
    }

    /**
     * Gets the value of the codErro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodErro() {
        return codErro;
    }

    /**
     * Sets the value of the codErro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodErro(String value) {
        this.codErro = value;
    }

}
