//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 11:28:55 AM BRST 
//


package br.com.getnet.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Grupo_ASCG026_PontoVendaComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Grupo_ASCG026_PontoVendaComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NumCtrlCreddrPontoVenda" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}ControleCIPCodErr"/>
 *         &lt;element name="CodInstitdrArrajPgtoAgend" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}CodInstitdrArrajPgtoCodErr"/>
 *         &lt;element name="CodMoeda" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}CodMoedaCodErr"/>
 *         &lt;element name="CodPontoVenda" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}CodPontoVendaCodErr"/>
 *         &lt;element name="TpPessoaPontoVenda" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}TpPessoaCodErr"/>
 *         &lt;element name="CNPJ_CPFPontoVenda" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}CNPJ_CPFCodErr"/>
 *         &lt;element name="DtPrevtPgto" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}DataCodErr"/>
 *         &lt;element name="VlrLiqdPgtoPrevt" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}ValorCodErr"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CodErro" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}CodErro" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Grupo_ASCG026_PontoVendaComplexType", propOrder = {
    "numCtrlCreddrPontoVenda",
    "codInstitdrArrajPgtoAgend",
    "codMoeda",
    "codPontoVenda",
    "tpPessoaPontoVenda",
    "cnpjcpfPontoVenda",
    "dtPrevtPgto",
    "vlrLiqdPgtoPrevt"
})
public class GrupoASCG026PontoVendaComplexType {

    @XmlElement(name = "NumCtrlCreddrPontoVenda", required = true)
    protected ControleCIPCodErr numCtrlCreddrPontoVenda;
    @XmlElement(name = "CodInstitdrArrajPgtoAgend", required = true)
    protected CodInstitdrArrajPgtoCodErr codInstitdrArrajPgtoAgend;
    @XmlElement(name = "CodMoeda", required = true)
    protected CodMoedaCodErr codMoeda;
    @XmlElement(name = "CodPontoVenda", required = true)
    protected CodPontoVendaCodErr codPontoVenda;
    @XmlElement(name = "TpPessoaPontoVenda", required = true)
    protected TpPessoaCodErr tpPessoaPontoVenda;
    @XmlElement(name = "CNPJ_CPFPontoVenda", required = true)
    protected CNPJCPFCodErr cnpjcpfPontoVenda;
    @XmlElement(name = "DtPrevtPgto", required = true)
    protected DataCodErr dtPrevtPgto;
    @XmlElement(name = "VlrLiqdPgtoPrevt", required = true)
    protected ValorCodErr vlrLiqdPgtoPrevt;
    @XmlAttribute(name = "CodErro")
    protected String codErro;

    /**
     * Gets the value of the numCtrlCreddrPontoVenda property.
     * 
     * @return
     *     possible object is
     *     {@link ControleCIPCodErr }
     *     
     */
    public ControleCIPCodErr getNumCtrlCreddrPontoVenda() {
        return numCtrlCreddrPontoVenda;
    }

    /**
     * Sets the value of the numCtrlCreddrPontoVenda property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControleCIPCodErr }
     *     
     */
    public void setNumCtrlCreddrPontoVenda(ControleCIPCodErr value) {
        this.numCtrlCreddrPontoVenda = value;
    }

    /**
     * Gets the value of the codInstitdrArrajPgtoAgend property.
     * 
     * @return
     *     possible object is
     *     {@link CodInstitdrArrajPgtoCodErr }
     *     
     */
    public CodInstitdrArrajPgtoCodErr getCodInstitdrArrajPgtoAgend() {
        return codInstitdrArrajPgtoAgend;
    }

    /**
     * Sets the value of the codInstitdrArrajPgtoAgend property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodInstitdrArrajPgtoCodErr }
     *     
     */
    public void setCodInstitdrArrajPgtoAgend(CodInstitdrArrajPgtoCodErr value) {
        this.codInstitdrArrajPgtoAgend = value;
    }

    /**
     * Gets the value of the codMoeda property.
     * 
     * @return
     *     possible object is
     *     {@link CodMoedaCodErr }
     *     
     */
    public CodMoedaCodErr getCodMoeda() {
        return codMoeda;
    }

    /**
     * Sets the value of the codMoeda property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodMoedaCodErr }
     *     
     */
    public void setCodMoeda(CodMoedaCodErr value) {
        this.codMoeda = value;
    }

    /**
     * Gets the value of the codPontoVenda property.
     * 
     * @return
     *     possible object is
     *     {@link CodPontoVendaCodErr }
     *     
     */
    public CodPontoVendaCodErr getCodPontoVenda() {
        return codPontoVenda;
    }

    /**
     * Sets the value of the codPontoVenda property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodPontoVendaCodErr }
     *     
     */
    public void setCodPontoVenda(CodPontoVendaCodErr value) {
        this.codPontoVenda = value;
    }

    /**
     * Gets the value of the tpPessoaPontoVenda property.
     * 
     * @return
     *     possible object is
     *     {@link TpPessoaCodErr }
     *     
     */
    public TpPessoaCodErr getTpPessoaPontoVenda() {
        return tpPessoaPontoVenda;
    }

    /**
     * Sets the value of the tpPessoaPontoVenda property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpPessoaCodErr }
     *     
     */
    public void setTpPessoaPontoVenda(TpPessoaCodErr value) {
        this.tpPessoaPontoVenda = value;
    }

    /**
     * Gets the value of the cnpjcpfPontoVenda property.
     * 
     * @return
     *     possible object is
     *     {@link CNPJCPFCodErr }
     *     
     */
    public CNPJCPFCodErr getCNPJCPFPontoVenda() {
        return cnpjcpfPontoVenda;
    }

    /**
     * Sets the value of the cnpjcpfPontoVenda property.
     * 
     * @param value
     *     allowed object is
     *     {@link CNPJCPFCodErr }
     *     
     */
    public void setCNPJCPFPontoVenda(CNPJCPFCodErr value) {
        this.cnpjcpfPontoVenda = value;
    }

    /**
     * Gets the value of the dtPrevtPgto property.
     * 
     * @return
     *     possible object is
     *     {@link DataCodErr }
     *     
     */
    public DataCodErr getDtPrevtPgto() {
        return dtPrevtPgto;
    }

    /**
     * Sets the value of the dtPrevtPgto property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataCodErr }
     *     
     */
    public void setDtPrevtPgto(DataCodErr value) {
        this.dtPrevtPgto = value;
    }

    /**
     * Gets the value of the vlrLiqdPgtoPrevt property.
     * 
     * @return
     *     possible object is
     *     {@link ValorCodErr }
     *     
     */
    public ValorCodErr getVlrLiqdPgtoPrevt() {
        return vlrLiqdPgtoPrevt;
    }

    /**
     * Sets the value of the vlrLiqdPgtoPrevt property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValorCodErr }
     *     
     */
    public void setVlrLiqdPgtoPrevt(ValorCodErr value) {
        this.vlrLiqdPgtoPrevt = value;
    }

    /**
     * Gets the value of the codErro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodErro() {
        return codErro;
    }

    /**
     * Sets the value of the codErro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodErro(String value) {
        this.codErro = value;
    }

}
