//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 11:28:55 AM BRST 
//


package br.com.getnet.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Grupo_ASCG026RET_CentrlzActoComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Grupo_ASCG026RET_CentrlzActoComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NumCtrlCreddrCentrlzActo" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}ControleIF"/>
 *         &lt;element name="NumCtrlCIPCentrlzActo" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}ControleCIP"/>
 *         &lt;element name="Grupo_ASCG026RET_PontoVendaActo" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}Grupo_ASCG026RET_PontoVendaActoComplexType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Grupo_ASCG026RET_CentrlzActoComplexType", propOrder = {
    "numCtrlCreddrCentrlzActo",
    "numCtrlCIPCentrlzActo",
    "grupoASCG026RETPontoVendaActo"
})
public class GrupoASCG026RETCentrlzActoComplexType {

    @XmlElement(name = "NumCtrlCreddrCentrlzActo", required = true)
    protected String numCtrlCreddrCentrlzActo;
    @XmlElement(name = "NumCtrlCIPCentrlzActo", required = true)
    protected String numCtrlCIPCentrlzActo;
    @XmlElement(name = "Grupo_ASCG026RET_PontoVendaActo", required = true)
    protected List<GrupoASCG026RETPontoVendaActoComplexType> grupoASCG026RETPontoVendaActo;

    /**
     * Gets the value of the numCtrlCreddrCentrlzActo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumCtrlCreddrCentrlzActo() {
        return numCtrlCreddrCentrlzActo;
    }

    /**
     * Sets the value of the numCtrlCreddrCentrlzActo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumCtrlCreddrCentrlzActo(String value) {
        this.numCtrlCreddrCentrlzActo = value;
    }

    /**
     * Gets the value of the numCtrlCIPCentrlzActo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumCtrlCIPCentrlzActo() {
        return numCtrlCIPCentrlzActo;
    }

    /**
     * Sets the value of the numCtrlCIPCentrlzActo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumCtrlCIPCentrlzActo(String value) {
        this.numCtrlCIPCentrlzActo = value;
    }

    /**
     * Gets the value of the grupoASCG026RETPontoVendaActo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the grupoASCG026RETPontoVendaActo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGrupoASCG026RETPontoVendaActo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GrupoASCG026RETPontoVendaActoComplexType }
     * 
     * 
     */
    public List<GrupoASCG026RETPontoVendaActoComplexType> getGrupoASCG026RETPontoVendaActo() {
        if (grupoASCG026RETPontoVendaActo == null) {
            grupoASCG026RETPontoVendaActo = new ArrayList<GrupoASCG026RETPontoVendaActoComplexType>();
        }
        return this.grupoASCG026RETPontoVendaActo;
    }

}
