//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 11:28:55 AM BRST 
//


package br.com.getnet.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Grupo_SeqComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Grupo_SeqComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NumSeq" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}NumSeq"/>
 *         &lt;element name="IndrCont" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}Indr"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Grupo_SeqComplexType", propOrder = {
    "numSeq",
    "indrCont"
})
public class GrupoSeqComplexType {

    @XmlElement(name = "NumSeq", required = true)
    protected BigInteger numSeq;
    @XmlElement(name = "IndrCont", required = true)
    protected Indr indrCont;

    /**
     * Gets the value of the numSeq property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumSeq() {
        return numSeq;
    }

    /**
     * Sets the value of the numSeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumSeq(BigInteger value) {
        this.numSeq = value;
    }

    /**
     * Gets the value of the indrCont property.
     * 
     * @return
     *     possible object is
     *     {@link Indr }
     *     
     */
    public Indr getIndrCont() {
        return indrCont;
    }

    /**
     * Sets the value of the indrCont property.
     * 
     * @param value
     *     allowed object is
     *     {@link Indr }
     *     
     */
    public void setIndrCont(Indr value) {
        this.indrCont = value;
    }

}
