//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 11:28:55 AM BRST 
//


package br.com.getnet.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Grupo_ASCG026RET_PontoVendaActoComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Grupo_ASCG026RET_PontoVendaActoComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NumCtrlCreddrPontoVendaActo" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}ControleIF"/>
 *         &lt;element name="NumCtrlCIPPontoVendaActo" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}ControleCIP"/>
 *         &lt;element name="DtHrManut" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}DataHora"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Grupo_ASCG026RET_PontoVendaActoComplexType", propOrder = {
    "numCtrlCreddrPontoVendaActo",
    "numCtrlCIPPontoVendaActo",
    "dtHrManut"
})
public class GrupoASCG026RETPontoVendaActoComplexType {

    @XmlElement(name = "NumCtrlCreddrPontoVendaActo", required = true)
    protected String numCtrlCreddrPontoVendaActo;
    @XmlElement(name = "NumCtrlCIPPontoVendaActo", required = true)
    protected String numCtrlCIPPontoVendaActo;
    @XmlElement(name = "DtHrManut", required = true)
    protected XMLGregorianCalendar dtHrManut;

    /**
     * Gets the value of the numCtrlCreddrPontoVendaActo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumCtrlCreddrPontoVendaActo() {
        return numCtrlCreddrPontoVendaActo;
    }

    /**
     * Sets the value of the numCtrlCreddrPontoVendaActo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumCtrlCreddrPontoVendaActo(String value) {
        this.numCtrlCreddrPontoVendaActo = value;
    }

    /**
     * Gets the value of the numCtrlCIPPontoVendaActo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumCtrlCIPPontoVendaActo() {
        return numCtrlCIPPontoVendaActo;
    }

    /**
     * Sets the value of the numCtrlCIPPontoVendaActo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumCtrlCIPPontoVendaActo(String value) {
        this.numCtrlCIPPontoVendaActo = value;
    }

    /**
     * Gets the value of the dtHrManut property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtHrManut() {
        return dtHrManut;
    }

    /**
     * Sets the value of the dtHrManut property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtHrManut(XMLGregorianCalendar value) {
        this.dtHrManut = value;
    }

}
