//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 11:28:55 AM BRST 
//


package br.com.getnet.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.getnet.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ASCGDOC_QNAME = new QName("http://www.cip-bancos.org.br/ARQ/ASCG026.xsd", "ASCGDOC");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.getnet.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ASCGDOCComplexType }
     * 
     */
    public ASCGDOCComplexType createASCGDOCComplexType() {
        return new ASCGDOCComplexType();
    }

    /**
     * Create an instance of {@link AgenciaCodErr }
     * 
     */
    public AgenciaCodErr createAgenciaCodErr() {
        return new AgenciaCodErr();
    }

    /**
     * Create an instance of {@link CNPJCodErr }
     * 
     */
    public CNPJCodErr createCNPJCodErr() {
        return new CNPJCodErr();
    }

    /**
     * Create an instance of {@link GrupoASCG026RETPontoVendaActoComplexType }
     * 
     */
    public GrupoASCG026RETPontoVendaActoComplexType createGrupoASCG026RETPontoVendaActoComplexType() {
        return new GrupoASCG026RETPontoVendaActoComplexType();
    }

    /**
     * Create an instance of {@link CodInstitdrArrajPgtoCodErr }
     * 
     */
    public CodInstitdrArrajPgtoCodErr createCodInstitdrArrajPgtoCodErr() {
        return new CodInstitdrArrajPgtoCodErr();
    }

    /**
     * Create an instance of {@link GrupoASCG026RETAgendRecsdoComplexType }
     * 
     */
    public GrupoASCG026RETAgendRecsdoComplexType createGrupoASCG026RETAgendRecsdoComplexType() {
        return new GrupoASCG026RETAgendRecsdoComplexType();
    }

    /**
     * Create an instance of {@link IndrFormaTransfCodErr }
     * 
     */
    public IndrFormaTransfCodErr createIndrFormaTransfCodErr() {
        return new IndrFormaTransfCodErr();
    }

    /**
     * Create an instance of {@link CodMoedaCodErr }
     * 
     */
    public CodMoedaCodErr createCodMoedaCodErr() {
        return new CodMoedaCodErr();
    }

    /**
     * Create an instance of {@link CodOcorcCodErr }
     * 
     */
    public CodOcorcCodErr createCodOcorcCodErr() {
        return new CodOcorcCodErr();
    }

    /**
     * Create an instance of {@link GrupoASCG026RETCentrlzActoComplexType }
     * 
     */
    public GrupoASCG026RETCentrlzActoComplexType createGrupoASCG026RETCentrlzActoComplexType() {
        return new GrupoASCG026RETCentrlzActoComplexType();
    }

    /**
     * Create an instance of {@link TpNatuGarCodErr }
     * 
     */
    public TpNatuGarCodErr createTpNatuGarCodErr() {
        return new TpNatuGarCodErr();
    }

    /**
     * Create an instance of {@link TpProdLiquidDebCodErr }
     * 
     */
    public TpProdLiquidDebCodErr createTpProdLiquidDebCodErr() {
        return new TpProdLiquidDebCodErr();
    }

    /**
     * Create an instance of {@link PercentualCodErr }
     * 
     */
    public PercentualCodErr createPercentualCodErr() {
        return new PercentualCodErr();
    }

    /**
     * Create an instance of {@link ControleCIPCodErr }
     * 
     */
    public ControleCIPCodErr createControleCIPCodErr() {
        return new ControleCIPCodErr();
    }

    /**
     * Create an instance of {@link GrupoASCG026CentrlzComplexType }
     * 
     */
    public GrupoASCG026CentrlzComplexType createGrupoASCG026CentrlzComplexType() {
        return new GrupoASCG026CentrlzComplexType();
    }

    /**
     * Create an instance of {@link TpBaixaDomclCodErr }
     * 
     */
    public TpBaixaDomclCodErr createTpBaixaDomclCodErr() {
        return new TpBaixaDomclCodErr();
    }

    /**
     * Create an instance of {@link NUCodErr }
     * 
     */
    public NUCodErr createNUCodErr() {
        return new NUCodErr();
    }

    /**
     * Create an instance of {@link DataCodErr }
     * 
     */
    public DataCodErr createDataCodErr() {
        return new DataCodErr();
    }

    /**
     * Create an instance of {@link CodPontoVendaCodErr }
     * 
     */
    public CodPontoVendaCodErr createCodPontoVendaCodErr() {
        return new CodPontoVendaCodErr();
    }

    /**
     * Create an instance of {@link NumIdentdResCodErr }
     * 
     */
    public NumIdentdResCodErr createNumIdentdResCodErr() {
        return new NumIdentdResCodErr();
    }

    /**
     * Create an instance of {@link ASCG026ComplexType }
     * 
     */
    public ASCG026ComplexType createASCG026ComplexType() {
        return new ASCG026ComplexType();
    }

    /**
     * Create an instance of {@link GrupoASCG026RETAgendActoComplexType }
     * 
     */
    public GrupoASCG026RETAgendActoComplexType createGrupoASCG026RETAgendActoComplexType() {
        return new GrupoASCG026RETAgendActoComplexType();
    }

    /**
     * Create an instance of {@link ValorCodErr }
     * 
     */
    public ValorCodErr createValorCodErr() {
        return new ValorCodErr();
    }

    /**
     * Create an instance of {@link TpProdLiquidCredCodErr }
     * 
     */
    public TpProdLiquidCredCodErr createTpProdLiquidCredCodErr() {
        return new TpProdLiquidCredCodErr();
    }

    /**
     * Create an instance of {@link NomArqCodErrComplexType }
     * 
     */
    public NomArqCodErrComplexType createNomArqCodErrComplexType() {
        return new NomArqCodErrComplexType();
    }

    /**
     * Create an instance of {@link NumIdentcDDACodErr }
     * 
     */
    public NumIdentcDDACodErr createNumIdentcDDACodErr() {
        return new NumIdentcDDACodErr();
    }

    /**
     * Create an instance of {@link CNPJCPFCodErr }
     * 
     */
    public CNPJCPFCodErr createCNPJCPFCodErr() {
        return new CNPJCPFCodErr();
    }

    /**
     * Create an instance of {@link SitPontoVendaCodErr }
     * 
     */
    public SitPontoVendaCodErr createSitPontoVendaCodErr() {
        return new SitPontoVendaCodErr();
    }

    /**
     * Create an instance of {@link ASCGDOCERRComplexType }
     * 
     */
    public ASCGDOCERRComplexType createASCGDOCERRComplexType() {
        return new ASCGDOCERRComplexType();
    }

    /**
     * Create an instance of {@link ASCG026RETComplexType }
     * 
     */
    public ASCG026RETComplexType createASCG026RETComplexType() {
        return new ASCG026RETComplexType();
    }

    /**
     * Create an instance of {@link CodIFCodErr }
     * 
     */
    public CodIFCodErr createCodIFCodErr() {
        return new CodIFCodErr();
    }

    /**
     * Create an instance of {@link CodRamoAtvddCodErr }
     * 
     */
    public CodRamoAtvddCodErr createCodRamoAtvddCodErr() {
        return new CodRamoAtvddCodErr();
    }

    /**
     * Create an instance of {@link GrupoASCG026CentrlzRecsdoComplexType }
     * 
     */
    public GrupoASCG026CentrlzRecsdoComplexType createGrupoASCG026CentrlzRecsdoComplexType() {
        return new GrupoASCG026CentrlzRecsdoComplexType();
    }

    /**
     * Create an instance of {@link AnoMesCodErr }
     * 
     */
    public AnoMesCodErr createAnoMesCodErr() {
        return new AnoMesCodErr();
    }

    /**
     * Create an instance of {@link CtBancariaCodErr }
     * 
     */
    public CtBancariaCodErr createCtBancariaCodErr() {
        return new CtBancariaCodErr();
    }

    /**
     * Create an instance of {@link NomeCodErr }
     * 
     */
    public NomeCodErr createNomeCodErr() {
        return new NomeCodErr();
    }

    /**
     * Create an instance of {@link CodProptEsqmCodErr }
     * 
     */
    public CodProptEsqmCodErr createCodProptEsqmCodErr() {
        return new CodProptEsqmCodErr();
    }

    /**
     * Create an instance of {@link GrupoSeqComplexType }
     * 
     */
    public GrupoSeqComplexType createGrupoSeqComplexType() {
        return new GrupoSeqComplexType();
    }

    /**
     * Create an instance of {@link TpMotvCodErr }
     * 
     */
    public TpMotvCodErr createTpMotvCodErr() {
        return new TpMotvCodErr();
    }

    /**
     * Create an instance of {@link ASCGDOCPROComplexType }
     * 
     */
    public ASCGDOCPROComplexType createASCGDOCPROComplexType() {
        return new ASCGDOCPROComplexType();
    }

    /**
     * Create an instance of {@link TpProdtCodErr }
     * 
     */
    public TpProdtCodErr createTpProdtCodErr() {
        return new TpProdtCodErr();
    }

    /**
     * Create an instance of {@link TpPessoaCodErr }
     * 
     */
    public TpPessoaCodErr createTpPessoaCodErr() {
        return new TpPessoaCodErr();
    }

    /**
     * Create an instance of {@link BCARQERRComplexType }
     * 
     */
    public BCARQERRComplexType createBCARQERRComplexType() {
        return new BCARQERRComplexType();
    }

    /**
     * Create an instance of {@link CNPJBaseCodErr }
     * 
     */
    public CNPJBaseCodErr createCNPJBaseCodErr() {
        return new CNPJBaseCodErr();
    }

    /**
     * Create an instance of {@link IndrCodErr }
     * 
     */
    public IndrCodErr createIndrCodErr() {
        return new IndrCodErr();
    }

    /**
     * Create an instance of {@link GrupoASCG026PontoVendaComplexType }
     * 
     */
    public GrupoASCG026PontoVendaComplexType createGrupoASCG026PontoVendaComplexType() {
        return new GrupoASCG026PontoVendaComplexType();
    }

    /**
     * Create an instance of {@link ControleIFCodErr }
     * 
     */
    public ControleIFCodErr createControleIFCodErr() {
        return new ControleIFCodErr();
    }

    /**
     * Create an instance of {@link BCARQComplexType }
     * 
     */
    public BCARQComplexType createBCARQComplexType() {
        return new BCARQComplexType();
    }

    /**
     * Create an instance of {@link SISARQComplexType }
     * 
     */
    public SISARQComplexType createSISARQComplexType() {
        return new SISARQComplexType();
    }

    /**
     * Create an instance of {@link GrupoASCG026AgendComplexType }
     * 
     */
    public GrupoASCG026AgendComplexType createGrupoASCG026AgendComplexType() {
        return new GrupoASCG026AgendComplexType();
    }

    /**
     * Create an instance of {@link CodCentrlzCodErr }
     * 
     */
    public CodCentrlzCodErr createCodCentrlzCodErr() {
        return new CodCentrlzCodErr();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ASCGDOCComplexType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cip-bancos.org.br/ARQ/ASCG026.xsd", name = "ASCGDOC")
    public JAXBElement<ASCGDOCComplexType> createASCGDOC(ASCGDOCComplexType value) {
        return new JAXBElement<ASCGDOCComplexType>(_ASCGDOC_QNAME, ASCGDOCComplexType.class, null, value);
    }

}
