//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 11:28:55 AM BRST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.cip-bancos.org.br/ARQ/ASCG026.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.com.getnet.xml;
