//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.09 at 11:28:55 AM BRST 
//


package br.com.getnet.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SISARQComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SISARQComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="ASCG026" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}ASCG026ComplexType"/>
 *         &lt;element name="ASCG026RET" type="{http://www.cip-bancos.org.br/ARQ/ASCG026.xsd}ASCG026RETComplexType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SISARQComplexType", propOrder = {
    "ascg026",
    "ascg026RET"
})
public class SISARQComplexType {

    @XmlElement(name = "ASCG026")
    protected ASCG026ComplexType ascg026;
    @XmlElement(name = "ASCG026RET")
    protected ASCG026RETComplexType ascg026RET;

    /**
     * Gets the value of the ascg026 property.
     * 
     * @return
     *     possible object is
     *     {@link ASCG026ComplexType }
     *     
     */
    public ASCG026ComplexType getASCG026() {
        return ascg026;
    }

    /**
     * Sets the value of the ascg026 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ASCG026ComplexType }
     *     
     */
    public void setASCG026(ASCG026ComplexType value) {
        this.ascg026 = value;
    }

    /**
     * Gets the value of the ascg026RET property.
     * 
     * @return
     *     possible object is
     *     {@link ASCG026RETComplexType }
     *     
     */
    public ASCG026RETComplexType getASCG026RET() {
        return ascg026RET;
    }

    /**
     * Sets the value of the ascg026RET property.
     * 
     * @param value
     *     allowed object is
     *     {@link ASCG026RETComplexType }
     *     
     */
    public void setASCG026RET(ASCG026RETComplexType value) {
        this.ascg026RET = value;
    }

}
